### PR TITLE
Title Stroke

### PR DESCRIPTION
**Pull request by shayanzoro**
Added stroke feature to all titles. Strokes are disabled by default.

### CODE REVIEW

**Comment by shayanzoro** [comment]
Here is the screenshot
[https://tinyjpg.com/site/output/eestl3p0ttrofeq2.jpg/title_with_stroke.jpg](url)

**Comment by shayanzoro** [comment]
@tangqi92 Hi. Can you please look at this PR?

**Comment by tangqi92** [comment]
Thank you for your PR ：）

**Comment by shayanzoro** [comment]
@tangqi92 Could you make a new release please?
I need this feature in my app.
Thanks

**Comment by tangqi92** [comment]
No problem, you will be notified after I finished.

**Comment by tangqi92** [comment]
@shayanzoro I have updated the library to v0.3.1

**Comment by tangqi92** [comment]
When your app is on the line, you can tell me, I want to add to the README

**Comment by shayanzoro** [comment]
@tangqi92 thanks! 
How can I help you with writing the README?

**Comment by tangqi92** [comment]
Tell me the name and link of your app

**Comment by shayanzoro** [comment]
It hasn't published yet. Would a screenshot help?

**Comment by tangqi92** [comment]
Well, I'll wait for you to finish the application, look forward to it：）

**Comment by shayanzoro** [comment]
Sure. Thanks. it aims the market of Iran and the language is Persian

**Pull request merged**
